# Generated by Django 4.2.4 on 2023-08-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
    ]
