# Generated by Django 4.2.4 on 2023-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
