# Generated by Django 4.2.4 on 2023-09-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
