# Generated by Django 4.2.4 on 2023-09-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
